server:
  port: 8082
  servlet:
    context-path: /materia
spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/materia?createDatabaseIfNotExist=true
    username: root
    password: 1234
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true


