server:
  port: 8082
  servlet:
    context-path: /materia
spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://:localhost:3307/materia
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver

